image: Visual Studio 2017

shallow_clone: true

install:
- ps: >-
    choco install rabbitmq -Version 3.4.1.0

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.RabbitMq -c Release 
  - dotnet build Rebus.RabbitMq.Tests -c Release 
